use ecu_board_profiles::TunerStudioProfileSelection;
use ecu_ts::pages::TS_PAGE_DESCRIPTORS;

use crate::{selection, ResolveError};

pub fn resolve_ts_asset_path(board: &str, recipe: &str) -> Result<String, ResolveError> {
    let plan = selection::resolve_plan(board, recipe)?;
    Ok(resolve_ts_asset_for_selection(plan.ts_profile)?.to_string())
}

pub fn resolve_ts_generated_path(board: &str, recipe: &str) -> Result<String, ResolveError> {
    let canonical = selection::canonical_selection(board, recipe)?;
    selection::resolve_plan(canonical.board, canonical.recipe)?;
    Ok(format!(
        "target/tunerstudio/{}/{}/ecu.ini",
        canonical.board, canonical.recipe
    ))
}

pub fn resolve_ts_generate_command(board: &str, recipe: &str) -> Result<String, ResolveError> {
    let path = resolve_ts_generated_path(board, recipe)?;
    assert_safe_path_fragment(board);
    assert_safe_path_fragment(recipe);
    assert_safe_path_fragment(&path);
    Ok(format!(
        "mkdir -p target/tunerstudio/{board}/{recipe} && cargo run -p ecu-firmware-resolver -- --ts-print-ini {board} {recipe} > {path}"
    ))
}

pub fn resolve_ts_ini(board: &str, recipe: &str) -> Result<String, ResolveError> {
    let canonical = selection::canonical_selection(board, recipe)?;
    let plan = selection::resolve_plan(canonical.board, canonical.recipe)?;
    let _ = resolve_ts_asset_for_selection(plan.ts_profile)?;
    Ok(render_generated_ini(canonical.board, canonical.recipe))
}

pub(crate) fn resolve_ts_asset_for_selection(
    selection: TunerStudioProfileSelection,
) -> Result<&'static str, ResolveError> {
    selection
        .profile_name()
        .ok_or(ResolveError::NoTunerStudioAsset { selection })
}

fn render_generated_ini(board: &str, recipe: &str) -> String {
    let mut out = String::new();
    out.push_str("; Generated by ecu-firmware-resolver\n");
    out.push_str(&format!("; board={board}\n; recipe={recipe}\n\n"));
    out.push_str("[MegaTune]\n");
    out.push_str("   MTversion = 2.25\n");
    out.push_str("   queryCommand = \"Q\"\n\n");
    out.push_str("[Constants]\n");
    out.push_str("   pageActivationDelay = 50\n");
    for descriptor in TS_PAGE_DESCRIPTORS {
        out.push_str(&format!(
            "   page = {}, \"{}\", {}, {}\n",
            descriptor.page,
            descriptor.label,
            descriptor.len,
            if descriptor.writable { "rw" } else { "ro" }
        ));
    }
    out.push_str("\n[OutputChannels]\n");
    out.push_str("   deadValue = { scalar, U08, 0, \"\", 0.0, 0.0 }\n");
    out.push_str("   rpm = { scalar, U16, 0, \"rpm\", 1.0, 0.0 }\n");
    out.push_str("   map = { scalar, U16, 2, \"kPa\", 1.0, 0.0 }\n\n");
    out.push_str("[GaugeConfigurations]\n");
    out.push_str("   gauge1 = rpmGauge, \"RPM\", \"rpm\", 0, 8000, 300, 7000, 7500, 8000, 0, 0\n");
    out.push_str("   gauge2 = mapGauge, \"MAP\", \"map\", 0, 300, 20, 200, 240, 300, 0, 0\n\n");
    out.push_str("[Menu]\n");
    for descriptor in TS_PAGE_DESCRIPTORS {
        out.push_str(&format!(
            "   menuDialog = page{}, \"{}\"\n",
            descriptor.page, descriptor.label
        ));
    }
    out
}

fn assert_safe_path_fragment(value: &str) {
    assert!(
        !value.is_empty(),
        "firmware resolver TS command fragment must not be empty"
    );
    assert!(
        value.bytes().all(is_safe_path_fragment_byte),
        "firmware resolver TS command fragment contains shell-sensitive characters: {value:?}"
    );
}

fn is_safe_path_fragment_byte(byte: u8) -> bool {
    matches!(
        byte,
        b'a'..=b'z'
            | b'A'..=b'Z'
            | b'0'..=b'9'
            | b'-'
            | b'_'
            | b'.'
            | b'/'
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[should_panic(expected = "shell-sensitive characters")]
    fn ts_command_fragments_reject_shell_sensitive_characters() {
        assert_safe_path_fragment("bad;rm");
    }
}
