[target.thumbv7em-none-eabihf]
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-dead-code=yes",
]

[target.thumbv6m-none-eabi]
rustflags = [
  "-C", "link-arg=-Tlink.x",
]

[llvm-cov]
workspace = false
